### PR TITLE
This fixes the code to work with EKS

### PR DESCRIPTION
**Pull request by eperdeme**
Code borrowed from https://github.com/morvencao/kube-mutating-webhook-tutorial/commit/2f484861b05645dc97e47feedf98e28caf00c034

### CODE REVIEW

**Comment by douglascamata** [comment]
Hey @eperdeme! It seems like the build is failing on all the 3 versions of k8s we test on.

Maybe this solution requires a minimum version of k8s to work? Can you investigate, please? 🙏 

Thanks!

**Comment by eperdeme** [comment]
Several commits later it should work now.

**Comment by eperdeme** [comment]
FYI, we've now replaced this function with jetstack/cert-manager

**Comment by pingnamo** [comment]
Thanks @eperdeme for the tips of using `cert-manger`.

It is easier to use cert manager to create the `newrelic-metadata-injection-secret` which contains `ca.crt` value and just need to copy that to `caBundle`.

**Comment by eperdeme** [comment]
Cert-manager has hooks to add CaBundle to any Webhooks for you. Really
makes the process easier.

**Comment by alejandrodnm** [comment]
We are going to hold this change until we test in openshift

**Comment by alejandrodnm** [comment]
The issue with EKS was fixed by #22 . This PR will let us save a call to kubectl by using the ca certificate that's mounted from the service account.

**Pull request merged**
